---
title: "Label_Transfer"
author: "Jenny Brown"
date: "28/01/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
neuron.AP <- readRDS(file="/nfsdata/projects/nvg559/data/mette_dvc/neurons_Seurat_obj.rds")
neuron.type.info <- readRDS("/projects/mludwig/Ludwig-2021/output/AUCell/neuron_type_info.rds")

neuron.AP$cell.subtype2 <- neuron.type.info$cell.type2[match(neuron.AP$cell.subtype,
                                                           neuron.type.info$cell.type)]
neuron.AP$cell.subtype2 <- factor(neuron.AP$cell.subtype2, 
                                  levels = neuron.type.info$cell.type2)

DefaultAssay(neuron.AP) <- "integrated"

DefaultAssay(t.dvc_Neurons) <- "RNA"
t.dvc_Neurons <- ScaleData(object = t.dvc_Neurons, verbose = F) 
t.dvc_Neurons <- RunPCA(object = t.dvc_Neurons, npcs = 30, verbose = FALSE)
t.dvc_Neurons <- RunUMAP(object = t.dvc_Neurons, reduction = "pca", 
                         dims = 1:30)
neuron.AP  <- ScaleData(object = neuron.AP, verbose = F)
neuron.AP <- RunPCA(object = neuron.AP, npcs = 30, verbose = FALSE)
neuron.AP <- RunUMAP(object = neuron.AP, reduction = "pca", 
                     dims = 1:30)
neuron.AP <- FindVariableFeatures(object = neuron.AP, 
                                  selection.method = "vst", nfeatures = 2000, 
                                  verbose = F)
t.dvc_Neurons <- FindVariableFeatures(object = t.dvc_Neurons, 
                                      selection.method = "vst", nfeatures = 2000, 
                                      verbose = F)

anchors <- FindTransferAnchors(reference = neuron.AP, query = t.dvc_Neurons, 
                               dims = 1:30, project.query = T, verbose = F)
predictions <- TransferData(anchorset = anchors, refdata = neuron.AP$cell.subtype2, 
                            dims = 1:30, verbose = F)

t.dvc_Neurons$predicted.id <- predictions$predicted.id
t.dvc_Neurons$prediction.score <- predictions$prediction.score.max
t.dvc_Neurons$predicted.id <- factor(t.dvc_Neurons$predicted.id, levels =c(paste0("Chat",seq(1:3)),
                                                                           paste0("GABA", seq(1:7)),
                                                                           paste0("Glu", seq(1:15))))

t.dvc_Neurons <- qread("/nfsdata/projects/nvg559/rike_data/new/neurons_merged_log_filt_integrated_labeled.qs")

```